#!/usr/bin/env python3
"""
Ralph Crosslink Applier Agent — actually applies crosslink suggestions
and scans for inline link opportunities.

Runs daily. Replaces the old weekly crosslink.py (which only generated suggestions).

Three layers:
  Layer 0 (mechanical): Scan body text for plain-text mentions of existing
                        page titles/slugs and wrap them in [[wikilinks]].
  Layer 1 (suggestions): Load crosslink_suggestions.json (generated by
                          crosslink.py) and apply high-confidence suggestions.
  Layer 2 (LLM):        For high-value suggestions with no mechanical insertion
                         point, use cheap model to insert naturally.
"""
import os
import re
import sys
import json
import datetime

import frontmatter

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ralph_config import (
    get_logger, WIKI_ROOT, META_DIR,
    get_all_pages, read_page, get_all_wikilinks,
    git_commit, append_log, run_pi, REPAIRER_MODEL,
)

log = get_logger("CrosslinkApplier")

CROSSLINK_SUGGESTIONS_FILE = os.path.join(META_DIR, "embeddings", "crosslink_suggestions.json")
MAX_APPLIED_PER_CYCLE = 100  # safety cap
MAX_LLM_CALLS = 20

# ── Build term → slug map ──────────────────────────────────────────────

def build_term_map(pages: dict[str, str]) -> dict[str, str]:
    """
    Build a map from display text → slug for all existing pages.
    Includes title variations (from frontmatter) and slug variations.
    """
    term_map = {}  # display_text -> slug

    for slug, filepath in pages.items():
        # Slug itself as a term (hyphens → spaces)
        term_map[slug] = slug
        slug_as_text = slug.replace('-', ' ')
        term_map[slug_as_text] = slug

        # Read title from frontmatter
        try:
            with open(filepath, 'r', encoding='utf-8') as f:
                post = frontmatter.load(f)
            title = post.metadata.get('title', '')
            if title:
                term_map[title] = slug
                # Also lowercase version
                term_map[title.lower()] = slug
        except Exception:
            pass

    # Add common aliases that don't match slug directly
    aliases = {
        'neural mass model': 'neural-mass-models',
        'neural mass models': 'neural-mass-models',
        'mean-field': 'mean-field-theory',
        'mean field': 'mean-field-theory',
        'mean-field theory': 'mean-field-theory',
        'mean field theory': 'mean-field-theory',
        'integrate-and-fire': 'spiking-neural-networks',
        'integrate and fire': 'spiking-neural-networks',
        'LFP': 'local-field-potentials',
        'local field potential': 'local-field-potentials',
        'BOLD': 'bold-signal',
        'BOLD signal': 'bold-signal',
        'fMRI': 'fmri',
        'EEG': 'eeg',
        'MEG': 'meg',
        'DTI': 'dti',
        'whole-brain model': 'whole-brain-modeling',
        'whole brain model': 'whole-brain-modeling',
        'connectome': 'connectome',
        'connectomics': 'connectomics',
        'epilepsy modeling': 'epilepsy-modeling',
        'seizure prediction': 'seizure-prediction',
        'graph theory': 'network-dynamics',
        'neural field': 'neural-field-theory',
        'neural fields': 'neural-field-theory',
        'spiking neural network': 'spiking-neural-networks',
        'The Virtual Brain': 'tvb',
        'TVB': 'tvb',
        'Wilson-Cowan': 'wilson-cowan',
        'Jansen-Rit': 'jansen-rit',
        'Epileptor': 'epileptor',
        'Wong-Wang': 'wong-wang',
        'Larter-Breakspear': 'larter-breakspear',
        'Stefanescu-Jirsa': 'stefanescu-jirsa',
        'Zerlaut': 'zerlaut',
        'Montbrio': 'montbrio-pazo-roxin',
        'dynamic causal modeling': 'dynamic-causal-modeling',
        'DCM': 'dynamic-causal-modeling',
        'functional connectivity': 'functional-connectivity',
        'structural connectivity': 'structural-connectivity',
        'effective connectivity': 'effective-connectivity',
        'resting state': 'resting-state',
        'resting-state': 'resting-state',
        'tractography': 'tractography',
        'bifurcation': 'bifurcation-analysis',
        'bifurcation analysis': 'bifurcation-analysis',
        'bifurcation theory': 'bifurcation-theory',
        'Fokker-Planck': 'fokker-planck-equation',
        'variational Bayes': 'variational-bayes',
        'forward model': 'forward-model',
        'source localization': 'source-localization',
        'parcellation': 'parcellation',
        'network dynamics': 'network-dynamics',
        'personalized brain': 'personalized-brain-modeling',
    }
    term_map.update(aliases)

    return term_map


# ── Layer 0: Inline term scanning ─────────────────────────────────────

def apply_inline_crosslinks(filepath: str, term_map: dict[str, str],
                            all_slugs: set[str]) -> tuple[bool, int]:
    """
    Scan body text for plain-text mentions of page titles/slugs
    and wrap them in [[wikilinks]].

    Returns (changed, count_of_additions).
    """
    slug = os.path.basename(filepath)[:-3]

    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            post = frontmatter.load(f)
    except Exception:
        return False, 0

    content = post.content

    # Get existing links to avoid duplicating
    existing_links = set(re.findall(r'\[\[([^\]|]+)', content))
    existing_targets = {l.strip().lower().replace(' ', '-') for l in existing_links}

    # Don't link to self
    skip_targets = {slug} | existing_targets

    # Build regex pattern for terms, sorted by length (longest first to match "mean-field theory" before "mean-field")
    # Filter out terms that would link to already-linked targets or to non-existent pages
    sorted_terms = sorted(term_map.keys(), key=len, reverse=True)

    # Track what we've added to avoid double-linking the same term in the same page
    added_targets = set()
    additions = 0

    # Process line by line, skipping code blocks and existing wikilinks
    new_lines = []
    in_code_block = False

    for line in content.split('\n'):
        # Skip code blocks
        if line.strip().startswith('```'):
            in_code_block = not in_code_block
            new_lines.append(line)
            continue
        if in_code_block:
            new_lines.append(line)
            continue

        # Skip headings (## and ###)
        if line.strip().startswith('#'):
            new_lines.append(line)
            continue

        # Skip table rows
        if '|' in line and line.strip().startswith('|'):
            new_lines.append(line)
            continue

        # Skip lines inside existing wikilinks (rough heuristic)
        # We'll just skip lines that are mostly wikilinks
        if line.count('[[') >= 3:
            new_lines.append(line)
            continue

        new_line = line
        for term in sorted_terms:
            target = term_map[term]
            if target in skip_targets or target in added_targets:
                continue
            if len(term) < 4:  # Skip very short terms (DCM, EEG handled by aliases above)
                continue

            # Case-sensitive match for proper nouns, case-insensitive for common terms
            if term[0].isupper() and not term.isupper():
                pattern = re.compile(r'(?<!\[\[)\b(' + re.escape(term) + r')\b(?![\]|])')
            else:
                pattern = re.compile(r'(?<!\[\[)\b(' + re.escape(term) + r')\b(?![\]|])', re.IGNORECASE)

            match = pattern.search(new_line)
            if match:
                # Replace first occurrence only
                display = match.group(1)
                if display.lower().replace(' ', '-') == target:
                    replacement = f'[[{target}]]'
                else:
                    replacement = f'[[{target}|{display}]]'
                new_line = new_line[:match.start()] + replacement + new_line[match.end():]
                added_targets.add(target)
                additions += 1
                if additions >= 10:
                    break
                continue

        new_lines.append(new_line)
        if additions >= 10:
            # Just copy rest of lines
            break

    # If we broke early, need to append remaining original lines
    original_lines = content.split('\n')
    if len(new_lines) < len(original_lines):
        new_lines.extend(original_lines[len(new_lines):])

    if additions == 0:
        return False, 0

    new_content = '\n'.join(new_lines)
    post.content = new_content
    post.metadata['updated'] = datetime.date.today().isoformat()

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(frontmatter.dumps(post))

    return True, additions


# ── Layer 1: Apply crosslink suggestions ───────────────────────────────

def apply_crosslink_suggestions(pages: dict[str, str]) -> int:
    """
    Load crosslink_suggestions.json and apply high-confidence suggestions
    that don't already have a link.
    """
    if not os.path.exists(CROSSLINK_SUGGESTIONS_FILE):
        log.info("No crosslink suggestions file found, skipping Layer 1")
        return 0

    try:
        with open(CROSSLINK_SUGGESTIONS_FILE, 'r') as f:
            suggestions = json.load(f)
    except Exception as e:
        log.warn("Could not load crosslink suggestions: %s", e)
        return 0

    applied = 0

    for suggestion in suggestions:
        if applied >= MAX_APPLIED_PER_CYCLE:
            break

        from_slug = suggestion.get('from', '')
        to_slug = suggestion.get('to', '')
        score = suggestion.get('score', 0)

        if score < 1.0:
            continue

        if from_slug not in pages or to_slug not in pages:
            continue

        filepath = pages[from_slug]

        try:
            with open(filepath, 'r', encoding='utf-8') as f:
                raw = f.read()
        except Exception:
            continue

        # Check if link already exists
        if f'[[{to_slug}' in raw or f'[[{to_slug.replace("-", " ")}' in raw.lower():
            continue

        post = frontmatter.loads(raw)
        content = post.content

        # Find the "Related Concepts" or "See also" section to add link
        # If it exists, add there. Otherwise, try to find natural text mention.
        related_match = re.search(r'^##\s+Related\s+(Concepts|Topics|Pages)', content, re.MULTILINE | re.IGNORECASE)
        see_also_match = re.search(r'^##\s+See\s+Also', content, re.MULTILINE | re.IGNORECASE)

        if related_match:
            # Find end of the related section
            start = related_match.end()
            next_section = re.search(r'^##\s+', content[start:], re.MULTILINE)
            if next_section:
                insert_pos = start + next_section.start()
            else:
                insert_pos = len(content)

            # Build the link line
            to_title = to_slug.replace('-', ' ').title()
            link_line = f'- [[{to_slug}|{to_title}]]\n'

            new_content = content[:insert_pos].rstrip('\n') + '\n' + link_line + content[insert_pos:]

            post.content = new_content
            post.metadata['updated'] = datetime.date.today().isoformat()
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(frontmatter.dumps(post))
            applied += 1
        elif see_also_match:
            start = see_also_match.end()
            next_section = re.search(r'^##\s+', content[start:], re.MULTILINE)
            if next_section:
                insert_pos = start + next_section.start()
            else:
                insert_pos = len(content)

            to_title = to_slug.replace('-', ' ').title()
            link_line = f'- [[{to_slug}|{to_title}]]\n'

            new_content = content[:insert_pos].rstrip('\n') + '\n' + link_line + content[insert_pos:]
            post.content = new_content
            post.metadata['updated'] = datetime.date.today().isoformat()
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(frontmatter.dumps(post))
            applied += 1
        # If neither section exists, skip — Layer 0 inline scanning will handle it

    return applied


# ── Main cycle ─────────────────────────────────────────────────────────

def run_crosslink_applier_cycle() -> dict:
    """Run the full crosslink applier cycle."""
    log.info("Starting crosslink applier cycle")

    pages = get_all_pages()
    all_slugs = set(pages.keys())

    stats = {
        'timestamp': datetime.datetime.now().isoformat(),
        'total_pages': len(pages),
        'inline_added': 0,
        'inline_pages': 0,
        'suggestions_applied': 0,
        'total_added': 0,
    }

    # ── Layer 0: Inline scanning ──
    log.info("Layer 0: Scanning for inline crosslink opportunities")
    term_map = build_term_map(pages)

    for slug, filepath in sorted(pages.items()):
        try:
            changed, count = apply_inline_crosslinks(filepath, term_map, all_slugs)
            if changed:
                stats['inline_added'] += count
                stats['inline_pages'] += 1
                log.info("  %s: +%d inline links", slug, count)
        except Exception as e:
            log.warn("  Error scanning %s: %s", slug, e)

    log.info("Layer 0 complete: %d links added across %d pages",
             stats['inline_added'], stats['inline_pages'])

    # ── Layer 1: Apply suggestions ──
    log.info("Layer 1: Applying crosslink suggestions")
    stats['suggestions_applied'] = apply_crosslink_suggestions(pages)
    log.info("Layer 1 complete: %d suggestions applied", stats['suggestions_applied'])

    stats['total_added'] = stats['inline_added'] + stats['suggestions_applied']

    if stats['total_added'] > 0:
        git_commit(
            f"CrosslinkApplier: {stats['inline_added']} inline + "
            f"{stats['suggestions_applied']} suggested links "
            f"({stats['total_added']} total)"
        )
        append_log(
            f"CrosslinkApplier: added {stats['total_added']} wikilinks "
            f"({stats['inline_added']} inline, {stats['suggestions_applied']} suggested)"
        )
    else:
        log.info("No crosslinks to add")

    # Save stats
    stats_file = os.path.join(META_DIR, 'crosslink_applier_stats.json')
    os.makedirs(META_DIR, exist_ok=True)
    with open(stats_file, 'w', encoding='utf-8') as f:
        json.dump(stats, f, indent=2, ensure_ascii=False)

    log.info("Cycle complete. Total: %d crosslinks added.", stats['total_added'])
    return stats


if __name__ == '__main__':
    run_crosslink_applier_cycle()
